### ISSUE TITLE
Less broken?

### ISSUE THREAD

**Issue by noelboss** [merkle-open/terrific-micro#10]
Maybe its just me, but the newest versions broke my code with anything containing @ in less... like

@font-face...

using an older (about e899aea7) app/ folder fixed it form me... Might be broken in some of the latest lessphp commits...

**Comment by ernscht** [comment]
I did not notice any errors with the less parser. I'm also using @font-face rules.

Can you give us more information, please?
* Any Error message?
* PHP Version, Webserver
* A new clone with the `Example` module is also broken?

**Comment by ernscht** [comment]
Everything ok?
Closing for now.
